[government]
title = "Starlight & Horizon - Current Government"
nation = "starlit_constellations"
category = "Meta/Reference"

[welcome_stl]
title = "Welcome to Starlight! (New players click here)"
nation = "starlit_constellations"
category = "Meta/Reference"

[welcome_hzn]
title = "Welcome to Horizon! (New players click here)"
nation = "sandy_wilds"
category = "Meta/Reference"