[armada_ranks]
title = "Galactic Armada - Ranks"
nation = "starlit_constellations"
category = "Meta/Reference"

[endotart]
title = "Biweekly Endorsement Competition - Win a Legendary Card!"
nation = "starlit_constellations"
category = "Bulletin/Campaign"
regenerate_after = 14

[foreign_affairs]
title = "Starlight & Horizon - Foreign Affairs"
nation = "starlit_constellations"
category = "Meta/Reference"

[government]
title = "Starlight & Horizon - Current Government"
nation = "starlit_constellations"
category = "Meta/Reference"

[hyperion_hzn]
title = "Horizon - Hyperion Guards"
nation = "sandy_wilds"
category = "Meta/Reference"

[hyperion_stl]
title = "Starlight - Hyperion Guards"
nation = "starlit_constellations"
category = "Meta/Reference"

[military]
title = "Starlight & Horizon - Galactic Armada"
nation = "starlit_constellations"
category = "Meta/Reference"

[slackers_hzn]
title = "Endorse the Delegate and Sentinels! (Click here)"
nation = "sandy_wilds"
category = "Bulletin/Campaign"
regenerate_after = 7

[slackers_stl]
title = "Endorse the Delegate and Sentinels! (Click here)"
nation = "starlit_constellations"
category = "Bulletin/Campaign"
regenerate_after = 7

[welcome_hzn]
title = "Welcome to Horizon! (New players click here)"
nation = "sandy_wilds"
category = "Meta/Reference"

[welcome_stl]
title = "Welcome to Starlight! (New players click here)"
nation = "starlit_constellations"
category = "Meta/Reference"

[wa_introduction]
title = "A Basic Guide to World Assembly Drafting"
nation = "starlit_constellations"
category = "Meta/Reference"
